[package]
name = "fibpetokenizer"
version = "0.1.1"
edition = "2021"
authors = ["Muhammad Faisal Ishfaq <faisalishfaq59@gmail.com>"]
description = "A blazing fast Byte Pair Encoding (BPE) tokenizer library with Python bindings"
license = "MIT OR Apache-2.0"
repository = "https://github.com/faisalishfaq2005/FIBpeTokenizer"
homepage = "https://github.com/faisalishfaq2005/FIBpeTokenizer"
documentation = "https://docs.rs/FIBpeTokenizer"
readme = "README.md"
keywords = ["tokenizer", "bpe", "nlp", "machine-learning", "text-processing"]
categories = ["text-processing", "algorithms", "data-structures"]

[lib]
name = "fibpetokenizer"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "fibpetokenizer"
path = "src/main.rs"

[dependencies]
rayon = "1.8"
aho-corasick = "1.1"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
pyo3 = { version = "0.22", features = ["extension-module"], optional = true }

[features]
default = []
python = ["pyo3"]

[profile.release]
opt-level = 3
lto = true
